### PR TITLE
Colorize http log

### LINKED ISSUE #7: Colorize HTTP log output

### PR DESCRIPTION
**Pull request by sh4869**
Closes #7

### CODE REVIEW

**Comment by makenowjust** [comment]
Please change message to "Closes #7" to close #7 automatically after merged.

**Comment by sh4869** [comment]
I changed my comment.

**Comment by makenowjust** [comment]
@sh4869 Could you run `make dep` to update dependencies?

**Comment by sh4869** [comment]
Add update dependencies commit.

**Comment by makenowjust** [comment]
Good 😆  Thank you for contributing!

**Pull request merged**
